/**
 * build.js - compile all TrustIQ JSX into a single plain-JS bundle.js.
 *
 * Concatenates the source files in dependency order, transforms JSX with
 * @babel/preset-react, and writes bundle.js. This removes the need for any
 * in-browser Babel compilation, which is the robust, production-style setup.
 *
 *   node build.js
 */
const babel = require("@babel/core");
const fs = require("fs");

// Order matters: core (window.TrustIQ) first, components next, mount last.
const FILES = [
  "app_core.jsx",
  "roster.jsx",
  "alert_feed.jsx",
  "customer_profile.jsx",
  "fraud_ring.jsx",
  "compliance_panel.jsx",
  "trust_score.jsx",
  "command_center.jsx",
  "dashboard.jsx",
  "mount.jsx",
];

const header = "/* TrustIQ bundle - generated by build.js. Do not edit directly. */\n";
const parts = [header];

for (const f of FILES) {
  const src = fs.readFileSync(f, "utf8");
  const out = babel.transformSync(src, {
    presets: ["@babel/preset-react"],
    filename: f,
  });
  parts.push(`\n/* ===== ${f} ===== */\n`);
  parts.push(out.code);
}

fs.writeFileSync("bundle.js", parts.join("\n"));
const bytes = fs.statSync("bundle.js").size;
console.log(`Wrote bundle.js (${bytes} bytes) from ${FILES.length} sources.`);
