services:
  - type: redis
    name: trustiq-redis
    ipAllowList: [] # Allows internal connections
    plan: free
  - type: web
    name: trustiq-backend
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: trustiq-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: trustiq-redis
          property: port
      - key: JWT_SECRET_KEY
        value: trustiq-secure-key-123
      - key: DATABASE_URL
        sync: false
